[package]
name = "infinity-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Domain-agnostic utility helpers for Infinity (time, id, ...)"

[dependencies]
uuid.workspace = true
chrono.workspace = true
serde = "1.0.228"
