[package]
name = "infinity-logger"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Enterprise tracing logger for Infinity"

[features]
default = ["console"]

# 控制台日志
console = []

# 文件日志
file = ["dep:tracing-appender"]

# JSON 日志
json = ["tracing-subscriber/json"]

# OpenTelemetry
otel = [
    "dep:opentelemetry",
    "dep:opentelemetry_sdk",
    "dep:tracing-opentelemetry",
]

# Axum 支持
axum = ["dep:tower-http"]

# Tonic 支持
grpc = ["dep:tonic"]

# 全部功能
full = ["console", "file", "json", "otel", "axum", "grpc"]
[dependencies]
# workspace 统一错误
infinity-error = { path = "../infinity-error" }

# tracing
tracing = "0.1"
tracing-core = "0.1"
tracing-log = "0.2"
tracing-error = "0.2"
tracing-subscriber = { version = "0.3", features = [
    "fmt",
    "env-filter",
    "registry",
    "json",
    "ansi",
    "time",
    "local-time",
] }

# file
tracing-appender = { version = "0.2", optional = true }
# error
thiserror = "2"

# config
serde = { version = "1", features = ["derive"] }
toml = "0.9"

# time
time = { version = "0.3", features = ["macros", "formatting", "local-offset"] }

# singleton
once_cell = "1"

# uuid
uuid = { version = "1", features = ["v4", "serde"] }

# opentelemetry
opentelemetry = { version = "0.32.0", optional = true }
opentelemetry_sdk = { version = "0.32", optional = true }

tracing-opentelemetry = { version = "0.33.0", optional = true }

# axum
tower-http = { version = "0.7.0", features = ["trace"], optional = true }

# grpc
tonic = { version = "0.14", optional = true }

# misc
hostname = "0.4"
parking_lot = "0.12"


[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
