[package]
name = "infinity-admin-server"
description = "Infinity admin management server"
readme = "README.md"
version = "0.1.1"
# version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "admin"
path = "src/main.rs"

[dependencies]
infinity-config = { path = "../../crates/infinity-config" }
infinity-logger = { path = "../../crates/infinity-logger" }
infinity-common = { path = "../../crates/infinity-common" }
infinity-utils = { path = "../../crates/infinity-utils" }
tracing.workspace = true
