[package]
name = "admin"
description = "Infinity admin management server"
readme = "README.md"
version = "0.1.1"
# version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "infinity-admin-server"
path = "src/main.rs"

[dependencies]
infinity-error = { path = "../../crates/infinity-error" }
infinity-config = { path = "../../crates/infinity-config" }
infinity-logger = { path = "../../crates/infinity-logger", features = [
    "axum",
    "json",
] }
infinity-utils = { path = "../../crates/infinity-utils" }
infinity-web = { path = "../../crates/infinity-web" }
infinity-proto = { path = "../../crates/infinity-proto" }
infinity-database = { path = "../../crates/infinity-database" }
infinity-auth = { path = "../../crates/infinity-auth" }

uuid.workspace = true
chrono.workspace = true

tracing.workspace = true
tokio.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true

# API Document
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
utoipa-axum.workspace = true
utoipa-redoc.workspace = true
utoipa-rapidoc.workspace = true
utoipa-scalar.workspace = true
# grpc
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection.workspace = true
prost-types = { workspace = true }

sqlx = { workspace = true }

validator = { workspace = true, features = ["derive"] }
async-trait = "0.1.89"
