[package]
name = "infinity-config"
description = "Layered configuration loading for Infinity"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
config = "0.15.25"
once_cell = "1.21.4"
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true
toml.workspace = true

tracing.workspace = true


