[package]
name = "infinity-web"
description = "Web/HTTP building blocks for Infinity"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
infinity-error = { path = "../infinity-error" }
serde.workspace = true
serde_with.workspace = true

axum.workspace = true

utoipa.workspace = true
serde_json.workspace = true

validator.workspace = true
chrono.workspace = true
