[package]
name = "infinity-erp-server"
description = "Infinity ERP service server"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "erp"
path = "src/main.rs"

[dependencies]
